### ISSUE TITLE
Jabber.org registrations closed

### ISSUE THREAD

**Issue by lloydwatkin** [duncan-bayne/duncan-bayne.github.com#7]
Hi,

In your wiki article (https://github.com/duncan-bayne/duncan-bayne.github.com/wiki/Why-I%27m-leaving-Google-Hangouts) you point people at jabber.org to get a new XMPP account, except registration is closed so that's not going to be any good.

It might be better to point people at the list of servers on the IM observatory which rates servers on security - https://xmpp.net/

Cheers, Lloyd.

**Comment by intosi** [comment]
Perhaps even to https://xmpp.net/directory.php, which is a list of public XMPP servers.

**Comment by duncan-bayne** [comment]
Thanks :)  I've updated the page.  Much appreciated.
